site_name: Módulo RK4

theme:
  name: "material"

nav:
  - index.md
  - explanation.md
  # - tutorials.md
  - reference.md

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
